### PR TITLE
Add a method CopyFromRemote

### PR DESCRIPTION
**Pull request by heicat**
use linux dd method

### CODE REVIEW

**Comment by bramvdbogaerde** [comment]
Thanks.
Please change the import paths back to this repository in order to get this merged.

**Comment by heicat** [comment]
@bramvdbogaerde 

it had already changed, sorry for two commits

**Comment by bramvdbogaerde** [comment]
No problem.
I will test your changes and merge them.

**Comment by EugenMayer** [comment]
That implementation is problematic since it buffers the whole file into the memory before writing it, ending up in a oom in cases

**Comment by bramvdbogaerde** [comment]
Because of the the following reasons, I will close this pull request because I think it would not be the ideal solution for the problem:
* Buffers the whole output of the dd command in a byte array in memory on the receiving side (our Golang program) as mentioned in an earlier comment
* Depends on external utility (ie. dd); maybe we could take a look at scp source mode (scp -f)

**Pull request closed without merging**
