### PR TITLE
Bugfix/scp multi files

### PR DESCRIPTION
**Pull request by qcha0**

### CODE REVIEW

**Comment by qcha0** [comment]
in my case, i want to copy multiple file at a time, just like
```golang
fun main() {
    ...
    client := scp.NewClient("example.com:22", &clientConfig)
    ...
    err := client.CopyFile(context.Background(), f1, "/tmp/1.txt", "0755")    // success
    ...
    err := client.CopyFile(context.Background(), f2, "/tmp/2.txt", "0755")    // failed, `ssh: StdoutPipe after process started`
}
```
so, i think should hold ssh client instead of ssh session.

In fact, I want to test it in fork repo first, pass it and then submit the pr.

**Comment by bramvdbogaerde** [comment]
Great! Please notify me whenever this is ready to merge.

**Comment by qcha0** [comment]
Has passed the test in the test environment

**Comment by zluther89** [comment]
@bramvdbogaerde any updates here? If I may suggest, @qcha0 you should add the tests into this PR to verify this works

**Comment by bramvdbogaerde** [comment]
Superseded by #70 .

**Pull request closed without merging**
