### PR TITLE
Fix for file names with space in them

### PR DESCRIPTION
**Pull request by JonasAlfredsson**
Use the %q syntax for [fmt][1] in order to create a quoted and escaped
string. This way we can both copy and write files which have a space in
them.

Disclosure: Technically it is not entirely correct to use %q here
since Go's quoting rules aren't identical to those of a shell, but
it's good enough.

[1]: https://golang.org/pkg/fmt/

### CODE REVIEW

**Comment by bramvdbogaerde** [comment]
This looks good. Could you also include a test for that (see tests/ directory), in particular it would be nice to check whether uploading/downloading files with a space in them works as intended.

**Comment by JonasAlfredsson** [comment]
There are some permission errors with the tests, but I can perhaps manage to create some kind of test tomorrow.

**Comment by bramvdbogaerde** [comment]
Great. If you need any assistance, please let me know.

**Comment by JonasAlfredsson** [comment]
There you go, I made the tests a little bit more compact as well so it looks like it is a bigger change than it is.

However, I cannot get this to work without also including https://github.com/bramvdbogaerde/go-scp/pull/42, just so you know.

**Comment by JonasAlfredsson** [comment]
It is also not optimal to run Go tests from bash, there are packages for Go where you can build and start your own container, but that is an even larger change for the future perhaps.

**Comment by bramvdbogaerde** [comment]
Thanks for your tests. I was planning to refactor the tests a bit to remove code duplication, but your changes look quite good.

I was also looking to integrate the Github Actions CI, but it seems rather difficult as we need to spawn docker containers in order to run a local SSH server. Maybe that is also something that can be fixed by spawning containers from Go itself, but indeed that is something that can be added in the future.

**Comment by JonasAlfredsson** [comment]
Yeah, I think it should be possible to start containers on the host machines running GitHub Actions, and since we don't need to expose the ports outside the localhost I suppose it will be much simpler.

I have this repository if you want some inspiration for some CI: https://github.com/JonasAlfredsson/docker-nginx-certbot
I also have a half finished repo where I communicate with Docker to do something similar to what you are trying to do. 
I don't have time to finish it right now, but I could perhaps ping you in the future if you don't get to it first :)

**Pull request merged**
